### ISSUE TITLE
Redesign of the "Manage permissions" side panel

### ISSUE THREAD

**Issue by juslar** [espresso-org/aragon-drive-app#17]
Modify to:
- 1 text input with a "Add" and "Remove" button
- 2 checkboxes to select "Read" or "Write" permissions
- 1 list with every address and "Read" or "Write" status

**Comment by macor161** [comment]
Something like this:

![manage-permissions](https://user-images.githubusercontent.com/642515/44676826-56ef9b00-aa02-11e8-9734-0428f252627b.jpg)
