### ISSUE TITLE
Configuration section should only close when transaction is complete

### ISSUE THREAD

**Issue by macor161** [espresso-org/aragon-drive-app#36]
### Configuration section should only close when transaction is complete

When a user clicks on the OK button of the Configuration section, it automatically closes before the app receives the transaction confirmation. This is not optimal since we don't know yet if the settings are actually saved. The user could cancel the transaction, a connection problem could happen or something else.

We should wait for the transaction confirmation to close the modal window.

### Steps to Reproduce

1. Open the configuration section
2. Change the settings
3. Click OK

**Expected behavior:** The modal window should only close when the transaction is complete.

**Actual behavior:** The modal window closes on click.

**Reproduces how often:** 100%

**Comment by juslar** [comment]
This is already fixed though I don't remember in which PR. I'll close this issue :)
